### ISSUE TITLE
最后的生成出错关于ninja.....sos已经折磨了我从昨晚到现在

### ISSUE THREAD

**Issue by DamienCz** [sdbds/TRELLIS-for-windows#10]
To create a public link, set share=True in launch().
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  9.80it/s]
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.61it/s]
Rendering: 120it [00:00, 175.27it/s]
G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\torch\utils\cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 2104, in _run_ninja_build
    subprocess.run(
  File "G:\sd_training_infor\python\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "G:\sd_training_infor\software\3Dmax\app.py", line 115, in image_to_3d
    video_geo = render_utils.render_video(outputs['mesh'][0], num_frames=120)['normal']
  File "G:\sd_training_infor\software\3Dmax\trellis\utils\render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
  File "G:\sd_training_infor\software\3Dmax\trellis\utils\render_utils.py", line 62, in render_frames
    renderer = MeshRenderer()
  File "G:\sd_training_infor\software\3Dmax\trellis\renderers\mesh_renderer.py", line 56, in __init__
    self.glctx = dr.RasterizeCudaContext(device=device)
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\nvdiffrast\torch\ops.py", line 184, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\nvdiffrast\torch\ops.py", line 125, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 1314, in load
    return _jit_compile(
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 1721, in _jit_compile
    _write_ninja_file_and_build_library(
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 1833, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "G:\sd_training_infor\software\3Dmax\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 2119, in _run_ninja_build
    message += f": {error.output.decode(*SUBPROCESS_DECODE_ARGS)}"  # type: ignore[union-attr]
  File "G:\sd_training_infor\python\lib\encodings\oem.py", line 15, in decode
    return oem_decode(input, errors, True)
UnicodeDecodeError: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

**Comment by sdbds** [comment]
https://www.bilibili.com/video/BV1Cui1YcEo1/
下载这个视频里面的国内专用免编译版本

**Comment by DamienCz** [comment]
> https://www.bilibili.com/video/BV1Cui1YcEo1/ 下载这个视频里面的国内专用免编译版本

我就是下的今早你更新到夸克的1.5 的....

**Comment by DamienCz** [comment]
![Uploading 微信截图_20241209145729.png…]()

**Comment by sdbds** [comment]
> > https://www.bilibili.com/video/BV1Cui1YcEo1/ 下载这个视频里面的国内专用免编译版本
> 
> 我就是下的今早你更新到夸克的1.5 的....

我更新了1.6，支持非sm8.9的显卡比如3090和2080TI

**Comment by DamienCz** [comment]
我使用了今早你更新的1.7....我发现可能不是其他的问题
于是我删掉了之前的cuda 12.1 删掉了anaconda，删掉了多余的python
总之排查了几乎所有的干扰项,但依旧
![image](https://github.com/user-attachments/assets/651e0547-15a9-45be-9bcc-553930a50971)
![image](https://github.com/user-attachments/assets/d9148003-a8f5-4977-94f0-4bec4a6e53fb)
![image](https://github.com/user-attachments/assets/f5ab0bc5-6409-4dbf-bace-bcc364112abf)
我是 4090 24G.... 1是直接编译成功了的
(3Dplus) PS D:\3Dplus> python -c "import torch; print(torch.__version__, torch.version.cuda)"
>>
2.5.1+cu124 12.4




> > > https://www.bilibili.com/video/BV1Cui1YcEo1/ 下载这个视频里面的国内专用免编译版本
> > 
> > 
> > 我就是下的今早你更新到夸克的1.5 的....
> 
> 我更新了1.6，支持非sm8.9的显卡比如3090和2080TI

**Comment by sdbds** [comment]
> 我使用了今早你更新的1.7....我发现可能不是其他的问题 于是我删掉了之前的cuda 12.1 删掉了anaconda，删掉了多余的python 总之排查了几乎所有的干扰项,但依旧 ![image](https://private-user-images.githubusercontent.com/132655237/394244646-651e0547-15a9-45be-9bcc-553930a50971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NTI5MTgsIm5iZiI6MTczMzg1MjYxOCwicGF0aCI6Ii8xMzI2NTUyMzcvMzk0MjQ0NjQ2LTY1MWUwNTQ3LTE1YTktNDViZS05YmNjLTU1MzkzMGE1MDk3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNzQzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTNhZmRhNzA2MWJiNzViYWYxNWNiY2I0ODM2OWMwOWVmNDJjY2YwN2JhZTI0YWM5MjFhYjg2ODI0NTY1OWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ybseAbSuIXUpXMw_ZrVx1W8vJBCAApdGhfTwVuMvBkg) ![image](https://private-user-images.githubusercontent.com/132655237/394244585-d9148003-a8f5-4977-94f0-4bec4a6e53fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NTI5MTgsIm5iZiI6MTczMzg1MjYxOCwicGF0aCI6Ii8xMzI2NTUyMzcvMzk0MjQ0NTg1LWQ5MTQ4MDAzLWE4ZjUtNDk3Ny05NGYwLTRiZWM0YTZlNTNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNzQzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYTczMzIzZDljZGFjY2ZjYTEyNzlkNjkwNGQyMTAwNzIxZDY5OGZjZjM3NTc0ZGEwM2M4ODFhNjkwZTE3ODcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9ypS9z5mV_xkJXRCI-QfehCNT54sll8k5TOim91tE2k) ![image](https://private-user-images.githubusercontent.com/132655237/394245899-f5ab0bc5-6409-4dbf-bace-bcc364112abf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NTI5MTgsIm5iZiI6MTczMzg1MjYxOCwicGF0aCI6Ii8xMzI2NTUyMzcvMzk0MjQ1ODk5LWY1YWIwYmM1LTY0MDktNGRiZi1iYWNlLWJjYzM2NDExMmFiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNzQzMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2IwZGM4N2QyNzEzNjhjNGQ4Yzc5N2Y0ZGFhYWFmMTJjNDc4NjYyMDFhZTdmY2U0Yzk1OWRlZDUyMzVmNmZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.O77LWijEkOzVbitDVtoEH3mxZE-xuwN24H13O0Yi6-A) 我是 4090 24G.... 1是直接编译成功了的 (3Dplus) PS D:\3Dplus> python -c "import torch; print(torch.**version**, torch.version.cuda)"
> 
> > >
> 
> 2.5.1+cu124 12.4
> 
> > > > https://www.bilibili.com/video/BV1Cui1YcEo1/ 下载这个视频里面的国内专用免编译版本
> > > 
> > > 
> > > 我就是下的今早你更新到夸克的1.5 的....
> > 
> > 
> > 我更新了1.6，支持非sm8.9的显卡比如3090和2080TI

uv pip list找一下那个丢失的模块，走的不是pip install，你pip install可能不成功。走uv pip install
