### ISSUE TITLE
TORCH_CUDA_ARCH_LIST  error

### ISSUE THREAD

**Issue by haruhix** [sdbds/TRELLIS-for-windows#11]
To create a public link, set `share=True` in `launch()`.
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:01<00:00,  6.88it/s]
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:03<00:00,  3.99it/s]
Rendering: 120it [00:00, 166.96it/s]
D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 2104, in _run_ninja_build
    subprocess.run(
  File "C:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\app.py", line 115, in image_to_3d
    video_geo = render_utils.render_video(outputs['mesh'][0], num_frames=120)['normal']
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\trellis\utils\render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\trellis\utils\render_utils.py", line 62, in render_frames
    renderer = MeshRenderer()
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\trellis\renderers\mesh_renderer.py", line 56, in __init__
    self.glctx = dr.RasterizeCudaContext(device=device)
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\torch\ops.py", line 184, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\torch\ops.py", line 125, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=common_opts+cc_opts, extra_cuda_cflags=common_opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 1314, in load
    return _jit_compile(
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 1721, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 1833, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\utils\cpp_extension.py", line 2120, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin': [1/16] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output RasterImpl.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\cudaraster\impl\RasterImpl.cu -o RasterImpl.cuda.o
FAILED: RasterImpl.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output RasterImpl.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\cudaraster\impl\RasterImpl.cu -o RasterImpl.cuda.o
CreateProcess failed: The system cannot find the file specified.
[2/16] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output rasterize.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\rasterize.cu -o rasterize.cuda.o
FAILED: rasterize.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output rasterize.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\rasterize.cu -o rasterize.cuda.o
CreateProcess failed: The system cannot find the file specified.
[3/16] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output interpolate.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\interpolate.cu -o interpolate.cuda.o
FAILED: interpolate.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output interpolate.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\interpolate.cu -o interpolate.cuda.o
CreateProcess failed: The system cannot find the file specified.
[4/16] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output texture.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\texture.cu -o texture.cuda.o
FAILED: texture.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output texture.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\texture.cu -o texture.cuda.o
CreateProcess failed: The system cannot find the file specified.
[5/16] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output antialias.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\antialias.cu -o antialias.cuda.o
FAILED: antialias.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\bin\nvcc --generate-dependencies-with-compile --dependency-output antialias.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=nvdiffrast_plugin -DTORCH_API_INCLUDE_EXTENSION_H -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\torch\csrc\api\include -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\TH -ID:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\include" -IC:\Users\admin\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_ninja: fatal: ReadFile: ðØðÁð▓ðÁÐÇð¢Ðïð╣ ð┤ðÁÐüð║ÐÇð©ð┐Ðéð¥ÐÇ.

89,code=sm_89 -std=c++17 -DNVDR_TORCH -lineinfo -c D:\AOD\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\common\antialias.cu -o antialias.cuda.o
CreateProcess failed: The system cannot find the file specified.

after starting the generation, I catch this bug

nvcc --version
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

nvidia-smi
Mon Dec  9 15:29:21 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.94                 Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080      WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   40C    P8             15W /  340W |   15364MiB /  16376MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

**Comment by haruhix** [comment]
![image](https://github.com/user-attachments/assets/b11ae659-1bf3-4e64-8707-dd491013c8ac)
I'm stupid, I uninstalled all other CUDAs and forgot to put CUDA HOME in the environment

**Comment by DamienCz** [comment]
HOW DID U FIX IT BRO....EVEN I PUT 
![image](https://github.com/user-attachments/assets/a04dd644-8c27-401b-aa4a-84d4df13bf0c)
CUDA HERE I STILL GET THIS ERROR...
![image](https://github.com/user-attachments/assets/50d1bff6-15a8-4fcc-9e38-e89665c1d60b)
