### ISSUE TITLE
'FlexiCubes' is not defined

### ISSUE THREAD

**Issue by oumad** [sdbds/TRELLIS-for-windows#12]
First if all, thank you so much for doing this for us windows users, really appreciated.

I started by running the `1、install-uv-qinglong.ps1`
I got "Install finished" with a couple sym link failures
I started the `2、run_gui.ps1`
then got
```
Windows .venv
[SPARSE] Backend: spconv, Attention: flash_attn
Please install kaolin and diso to use the mesh extractor.
Warp 1.5.0 initialized:
   CUDA Toolkit 12.6, Driver 12.7
   Devices:
     "cpu"      : "Intel64 Family 6 Model 183 Stepping 1, GenuineIntel"
     "cuda:0"   : "NVIDIA GeForce RTX 4090" (24 GiB, sm_89, mempool enabled)
   Kernel cache:
     C:\Users\home\AppData\Local\NVIDIA\warp\Cache\1.5.0
C:\palette\apl\TRELLIS-for-windows\.venv\lib\site-packages\gradio_client\utils.py:1097: UserWarning: file() is deprecated and will be removed in a future version. Use handle_file() instead.
  warnings.warn(
[SPARSE][CONV] spconv algo: auto
[ATTENTION] Using backend: flash_attn
Traceback (most recent call last):
  File "C:\palette\apl\TRELLIS-for-windows\app.py", line 246, in <module>
    pipeline = TrellisImageTo3DPipeline.from_pretrained("JeffreyXiang/TRELLIS-image-large")
  File "C:\palette\apl\TRELLIS-for-windows\trellis\pipelines\trellis_image_to_3d.py", line 55, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
  File "C:\palette\apl\TRELLIS-for-windows\trellis\pipelines\base.py", line 39, in from_pretrained
    _models = {
  File "C:\palette\apl\TRELLIS-for-windows\trellis\pipelines\base.py", line 40, in <dictcomp>
    k: models.from_pretrained(f"{path}/{v}")
  File "C:\palette\apl\TRELLIS-for-windows\trellis\models\__init__.py", line 59, in from_pretrained
    model = __getattr__(config['name'])(**config['args'], **kwargs)
  File "C:\palette\apl\TRELLIS-for-windows\trellis\models\structured_latent_vae\decoder_mesh.py", line 105, in __init__
    self.mesh_extractor = SparseFeatures2Mesh(res=self.resolution*4, use_color=self.rep_config.get('use_color', False))
  File "C:\palette\apl\TRELLIS-for-windows\trellis\representations\mesh\cube2mesh.py", line 69, in __init__
    self.mesh_extractor = FlexiCubes(device=device)
NameError: name 'FlexiCubes' is not defined
```

I deleted the .env and tried installing again as admin, didn't get the symlink errors, but starting the gui script yielded the same error as above.

Anyone facing a similar issue ?

**Comment by sdbds** [comment]
`git clone --recurse-submodules https://github.com/sdbds/TRELLIS-for-windows.git`

special use ` --recurse-submodules`

**Comment by oumad** [comment]
> `git clone --recurse-submodules https://github.com/sdbds/TRELLIS-for-windows.git`
> 
> special use ` --recurse-submodules`

Cool, I deleted everything and cloned the repo using with the submodules parameter and re-run the scripts, it works fine now ! Thank you
