### ISSUE TITLE
RuntimeError: Could not locate a supported Microsoft Visual C++ installation

### ISSUE THREAD

**Issue by alexdepario** [sdbds/TRELLIS-for-windows#15]
I have a issue when trying to generate the 3d asset. It all starts well with: 
Warp 1.5.0 initialized:
   CUDA Toolkit 12.6, Driver 12.7
   Devices:
     "cpu"      : "Intel64 Family 6 Model 151 Stepping 2, GenuineIntel"
     "cuda:0"   : "NVIDIA GeForce RTX 3090 Ti" (24 GiB, sm_86, mempool enabled)

But then when I click the Generate button.............
To create a public link, set `share=True` in `launch()`.
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:02<00:00,  4.01it/s]
Sampling: 100%|████████████████████████████████████████████████████████████████████████| 12/12 [00:08<00:00,  1.43it/s]
Rendering: 120it [00:01, 83.78it/s]
Traceback (most recent call last):
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1005, in run
    result = context.run(func, *args)
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "F:\TRELLIS\TRELLIS-for-windows\app.py", line 115, in image_to_3d
    video_geo = render_utils.render_video(outputs['mesh'][0], num_frames=120)['normal']
  File "F:\TRELLIS\TRELLIS-for-windows\trellis\utils\render_utils.py", line 96, in render_video
    return render_frames(sample, extrinsics, intrinsics, {'resolution': resolution, 'bg_color': bg_color}, **kwargs)
  File "F:\TRELLIS\TRELLIS-for-windows\trellis\utils\render_utils.py", line 62, in render_frames
    renderer = MeshRenderer()
  File "F:\TRELLIS\TRELLIS-for-windows\trellis\renderers\mesh_renderer.py", line 56, in __init__
    self.glctx = dr.RasterizeCudaContext(device=device)
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\torch\ops.py", line 184, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeCRStateWrapper(cuda_device_idx)
  File "F:\TRELLIS\TRELLIS-for-windows\.venv\lib\site-packages\nvdiffrast\torch\ops.py", line 47, in _get_plugin
    raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
RuntimeError: Could not locate a supported Microsoft Visual C++ installation

I have Visual C++ 2015-2022 Redistribulable, 2013 Redistribulable, 2012 Redistribulable and 2008 Redistribulable both for x86 and x64 installed.

**Comment by alexdepario** [comment]
Nevermind, I fixed it by installing Visual Studio Build Tools 
During installation, I explicitly select:
"Desktop development with C++" workload
MSVC v143  build tools
Windows 10/11 SDK 

Then when i executed the 2、run_gui again and it was fixed
