### ISSUE TITLE
help me~？

### ISSUE THREAD

**Issue by tiandaoyuxi** [sdbds/TRELLIS-for-windows#20]
UV cache directory already exists, skipping disk space check
uv 0.5.11 (c4d0caaee 2024-12-19)
uv installed|UV模块已安装.
Windows .venv
Installing main requirements
Resolved 2 packages in 1.72s
  x Failed to download `wheel==0.45.1`
  |-> Failed to read from the distribution cache
  `-> 此文件或目录不是一个重分析点。 (os error 4390)
Resolved 122 packages in 2.08s
  x Failed to build `utils3d @
  | git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8`
  |-> The build backend returned an error
  `-> Call to `setuptools.build_meta.build_wheel` failed (exit code: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'setuptools'

      hint: This usually indicates a problem with the package or the build environment.
Install main requirements failed
Install failed|安装失败。

**Comment by grandmazboy** [comment]
had a couple of issues and started fresh..
- Open an administrator powershell window
- Type `Set-ExecutionPolicy Unrestricted` and answer A
- Close admin powershell window
- git clone --recurse-submodules https://github.com/sdbds/TRELLIS-for-windows.git
- python -m venv E:\TRELLIS-for-windows-main\.venv
- E:\TRELLIS-for-windows-main\.venv\Scripts\Activate.ps1
- In windows explorer run 1、install-uv-qinglong.ps1 with right click run with powershell
- I opened new powershell window
- E:\TRELLIS-for-windows-main\.venv\Scripts\Activate.ps1 or .venv\Scripts\Activate.ps1 if in your TRELLIS directory
- Once it finished right click 2、run_gui.ps1 run with powershell

**Comment by tiandaoyuxi** [comment]
> * python -m venv E:\TRELLIS-for-windows-main.venv

![image](https://github.com/user-attachments/assets/fb38d575-a645-42e8-8c33-0e473f5bd1c8)
I couldn't find this fileTRELLIS-for-windows-main.venv

**Comment by tiandaoyuxi** [comment]
I couldn't find this fileTRELLIS-for-windows-main.venv
So I replaced the command
1、python -m venv E:\TRELLIS-for-windows-main.venv   ->python -m venv venv
2、E:\TRELLIS-for-windows-main.venv\Scripts\Activate.ps1 ->venv\Scripts\activate

In windows explorer run 1、install-uv-qinglong.ps1 with right click run with powershell
I opened new powershell window
E:\TRELLIS-for-windows-main.venv\Scripts\Activate.ps1 or .venv\Scripts\Activate.ps1 if in your TRELLIS directory
Once it finished right click 2、run_gui.ps1 run with powershell

UV cache directory already exists, skipping disk space check
uv 0.5.11 (c4d0caaee 2024-12-19)
uv installed|UV模块已安装.
Windows venv
Installing main requirements
Using Python 3.12.6 environment at: venv
Resolved 2 packages in 2.75s
  x Failed to download `wheel==0.45.1`
  |-> Failed to read from the distribution cache
  `-> 此文件或目录不是一个重分析点。 (os error 4390)
Using Python 3.12.6 environment at: venv
  x No solution found when resolving dependencies:
  `-> Because cumm-cu120==0.4.11 has no wheels with a matching Python ABI tag and you require
      cumm-cu120==0.4.11, we can conclude that your requirements are unsatisfiable.
Install main requirements failed
Install failed|安装失败。

----------------------------
Windows PowerShell
版权所有（C） Microsoft Corporation。保留所有权利。

安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

加载个人及系统配置文件用了 512 毫秒。
(base) PS C:\Windows\system32> g:
(base) PS G:\> cd .\TRELLIS-for-windows\
(base) PS G:\TRELLIS-for-windows> .\venv\Scripts\activate
(venv) (base) PS G:\TRELLIS-for-windows> .\1、install-uv-qinglong.ps1
UV cache directory already exists, skipping disk space check
uv 0.5.11 (c4d0caaee 2024-12-19)
uv installed|UV模块已安装.
Windows venv
Installing main requirements
Using Python 3.12.6 environment at: venv
Resolved 2 packages in 1.83s
  x Failed to download `wheel==0.45.1`
  |-> Failed to read from the distribution cache
  `-> 此文件或目录不是一个重分析点。 (os error 4390)
Using Python 3.12.6 environment at: venv
  x No solution found when resolving dependencies:
  `-> Because cumm-cu120==0.4.11 has no wheels with a matching Python ABI tag and you require cumm-cu120==0.4.11, we
      can conclude that your requirements are unsatisfiable.
Install main requirements failed
Install failed|安装失败。

**Comment by tiandaoyuxi** [comment]
(base) PS C:\Users\win11> conda create -n trellis python=3.11
Retrieving notices: ...working... done
WARNING: A conda environment already exists at 'C:\Users\win11\.conda\envs\trellis'
Remove existing environment (y/[n])? Y

Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: done

 Package Plan 

  environment location: C:\Users\win11\.conda\envs\trellis

  added / updated specs:
    - python=3.11


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.11.11             |       h4607a30_0        18.7 MB
    ------------------------------------------------------------
                                           Total:        18.7 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-h2bbff1b_6
  ca-certificates    pkgs/main/win-64::ca-certificates-2024.11.26-haa95532_0
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_1
  openssl            pkgs/main/win-64::openssl-3.0.15-h827c3e9_0
  pip                pkgs/main/win-64::pip-24.2-py311haa95532_0
  python             pkgs/main/win-64::python-3.11.11-h4607a30_0
  setuptools         pkgs/main/win-64::setuptools-75.1.0-py311haa95532_0
  sqlite             pkgs/main/win-64::sqlite-3.45.3-h2bbff1b_0
  tk                 pkgs/main/win-64::tk-8.6.14-h0416ee5_0
  tzdata             pkgs/main/noarch::tzdata-2024b-h04d1e81_0
  vc                 pkgs/main/win-64::vc-14.40-haa95532_2
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.42.34433-h9531ae6_2
  wheel              pkgs/main/win-64::wheel-0.44.0-py311haa95532_0
  xz                 pkgs/main/win-64::xz-5.4.6-h8cc25b3_1
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_1


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

 To activate this environment, use

     $ conda activate trellis

 To deactivate an active environment, use

     $ conda deactivate

(base) PS C:\Users\win11> conda activate trellis
(trellis) PS C:\Users\win11> g:
(trellis) PS G:\> cd .\TRELLIS-for-windows\
(trellis) PS G:\TRELLIS-for-windows> conda activate trellis
(trellis) (TRELLIS-for-windows) PS G:\TRELLIS-for-windows> python
Python 3.10.16 (main, Dec 19 2024, 14:31:40) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z
(trellis) (TRELLIS-for-windows) PS G:\TRELLIS-for-windows> .\1、install-uv-qinglong.ps1
UV cache directory already exists, skipping disk space check
uv 0.5.11 (c4d0caaee 2024-12-19)
uv installed|UV模块已安装.
Windows .venv
Installing main requirements
Resolved 2 packages in 1.42s
  x Failed to download `wheel==0.45.1`
  |-> Failed to read from the distribution cache
  `-> 此文件或目录不是一个重分析点。 (os error 4390)
Resolved 122 packages in 1.75s
  x Failed to build `utils3d @
  | git+https://github.com/EasternJournalist/utils3d.git@9a4eb15e4021b67b12c460c7057d642626897ec8`
  |-> The build backend returned an error
  `-> Call to `setuptools.build_meta.build_wheel` failed (exit code: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'setuptools'

      hint: This usually indicates a problem with the package or the build environment.
Install main requirements failed
Install failed|安装失败。

**Comment by sdbds** [comment]
It looks like your original python is incomplete.

**Comment by tiandaoyuxi** [comment]
> It looks like your original python is incomplete.

请问大佬Python版本要求是？我独立去安装一个之后再试试、
我用venv 和conda指定版本做虚拟环境都失败了。
