### ISSUE TITLE
Please install kaolin and diso to use the mesh extractor.

### ISSUE THREAD

**Issue by ioritree** [sdbds/TRELLIS-for-windows#9]
```
Please install kaolin and diso to use the mesh extractor.
Warp 1.5.0 initialized:
   CUDA Toolkit 12.6, Driver 12.7
   Devices:
     "cpu"      : "Intel64 Family 6 Model 158 Stepping 10, GenuineIntel"
     "cuda:0"   : "NVIDIA GeForce RTX 3090" (24 GiB, sm_86, mempool enabled)
   Kernel cache:
     C:\Users\******\AppData\Local\NVIDIA\warp\Cache\1.5.0
G:\TRELLIS-for-windows\.venv\lib\site-packages\gradio_client\utils.py:1097: UserWarning: file() is deprecated and will be removed in a future version. Use handle_file() instead.
  warnings.warn(
[SPARSE][CONV] spconv algo: auto
[ATTENTION] Using backend: flash_attn
Traceback (most recent call last):
  File "G:\TRELLIS-for-windows\app.py", line 246, in <module>
    pipeline = TrellisImageTo3DPipeline.from_pretrained("JeffreyXiang/TRELLIS-image-large")
  File "G:\TRELLIS-for-windows\trellis\pipelines\trellis_image_to_3d.py", line 55, in from_pretrained
    pipeline = super(TrellisImageTo3DPipeline, TrellisImageTo3DPipeline).from_pretrained(path)
  File "G:\TRELLIS-for-windows\trellis\pipelines\base.py", line 39, in from_pretrained
    _models = {
  File "G:\TRELLIS-for-windows\trellis\pipelines\base.py", line 40, in <dictcomp>
    k: models.from_pretrained(f"{path}/{v}")
  File "G:\TRELLIS-for-windows\trellis\models\__init__.py", line 59, in from_pretrained
    model = __getattr__(config['name'])(**config['args'], **kwargs)
  File "G:\TRELLIS-for-windows\trellis\models\structured_latent_vae\decoder_mesh.py", line 105, in __init__
    self.mesh_extractor = SparseFeatures2Mesh(res=self.resolution*4, use_color=self.rep_config.get('use_color', False))
  File "G:\TRELLIS-for-windows\trellis\representations\mesh\cube2mesh.py", line 69, in __init__
    self.mesh_extractor = FlexiCubes(device=device)
NameError: name 'FlexiCubes' is not defined
```

要怎麼解決呢

**Comment by sdbds** [comment]
检查是否使用的git clone --recurse-submodules https://github.com/sdbds/TRELLIS-for-windows.git
 --recurse-submodules才可以下载完整代码

**Comment by ioritree** [comment]
> 检查是否使用的git clone --recurse-submodules https://github.com/sdbds/TRELLIS-for-windows.git --recurse-submodules才可以下载完整代码


在install-uv-qinglong.ps1 底下添加兩行就好了
git submodule init 
git submodule update
